name: 'SafeguardDotNet merge publish pipeline'
variables:
  semanticVersion: "6.9.0"
  isPrerelease: ${{ true }}
trigger:
  branches:
    include:
    - master
    - release-*
  paths:
    exclude:
    - README.md
pr: none
jobs:
  - template: build.yml
  - job:
    displayName: 'Publishing packages to NuGet.org'
    - task: NuGetAuthenticate@0
      inputs:
        nuGetServiceConnections: 'SafeguardNuGetOrgServiceConnection'

    - task: NuGetCommand@2
      inputs:
        command: 'push'
        nuGetFeedType: 'external'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        verbosityPush: 'Detailed'
      displayName: 'Publishing NuGet packages to NuGet.org'
