# pr trigger
pr:
  branches:
    include:
    - master
    - release-*
  paths:
    exclude:
    - README.md

jobs:
  - template: build.yml

# merge trigger
trigger:
  branches:
    include:
    - master
    - release-*
  paths:
    exclude:
    - README.md

jobs:
  - template: build.yml
  - task: NuGetAuthenticate@0
    inputs:
      nuGetServiceConnections: 'SafeguardNuGetOrgServiceConnection'
    condition: and(succeeded(), eq(variables.isReleaseBranch, true))

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      nuGetFeedType: 'external'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      verbosityPush: 'Detailed'
    displayName: 'Publishing NuGet packages to NuGet.org'
  condition: and(succeeded(), eq(variables.isReleaseBranch, true))
