variables:
  - template: pipeline-templates/global-variables.yml
trigger:
  branches:
    include:
      - master
      - release-*
  paths:
    exclude:
      - README.md
pr:
  branches:
    include:
      - master
      - release-*
  paths:
    exclude:
      - README.md
jobs:
  - job: Build
    displayName: 'Build .NET Standard SDK and .NET Framework GUI component'
    variables:
      - template: pipeline-templates/job-variables.yml
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: pipeline-templates/build-steps.yml
